title: Siddhartha Malladi
url: "https://msiddhu.github.io"
remote_theme: ankitsultana/researcher@gem

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "Resume"
   link: "https://drive.google.com/file/d/1mSi-fGxzB-Yfuvy1sVJx8n_zNF8zPaR3/view?usp=sharing"
 - name: "Contact"
   link: "contact"
